[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar --spring.profiles.active=prod"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100